from django.urls import path
from .views import home, contact, menu, general_breakfast,north_indianbreakfast,south_indian_breakfast,starter,soup,salad,nsgravy,randb,tandoori,bread,noodles,momo,pizza,pasta,sizzler,lasagna,sandw,smoothie,specaildesert,laasi,aeratedbeverage,bakerysweets,burger,coffee,coldcoffee,freshjuice,fruitssalad,fruitswine,healthyjuice,healthysalad,hotdrink,icetea,mocktail,pancakes,raita,shake,bands

urlpatterns = [
    path("", home, name="home"),
    path("menu/", menu, name="menu"),
    path("menu/general-breakfast", general_breakfast, name="general-breakfast"),
    path("contact/", contact, name="contact"),
    path("menu/north_indianbreakfast", north_indianbreakfast, name="north_indianbreakfast"),
    path("menu/south-indian-breakfast", south_indian_breakfast, name="south_indianbreakfast"),
    path("menu/starter",starter,name="starter"),
    path("menu/soup",soup,name="soup"),
    path("menu/salad",salad,name="salad"),
    path("menu/nsgravy",nsgravy,name="nsgravy"),
    path("menu/randb",randb,name="randb"),
    path("menu/tandoori",tandoori,name="tandoori"),
    path("menu/bread",bread,name="bread"),
    path("menu/noodles",noodles,name="noodles"),
    path("menu/momo",momo,name="momo"),
    path("menu/pizza",pizza,name="pizza"),
    path("menu/pasta",pasta,name="pasta"),
    path("menu/sizzler",sizzler,name="sizzler"),
    path("menu/lasagna",lasagna,name="lasagna"),
    path("menu/sandw",sandw,name="sandw"),
    path("menu/smoothie",smoothie,name="smoothie"),
    path("menu/specialdesert",specaildesert,name="specialdesert"),
    path("menu/laasi",laasi,name="laasi"),
    path("menu/aeratedbeverage",aeratedbeverage,name="aeratedbeverage"),
    path("menu/bakerysweets",bakerysweets,name="bakerysweets"),
    path("menu/burger",burger,name="burger"),
    path("menu/coffee",coffee,name="coffee"),
    path("menu/coldcoffee",coldcoffee,name="coldcoffee"),
    path("menu/freshjuice",freshjuice,name="freshjuice"),
    path("menu/fruitssalad",fruitssalad,name="fruitssalad"),
    path("menu/fruitswine",fruitswine,name="fruitswine"),
    path("menu/healthyjuice",healthyjuice,name="healthyjuice"),
    path("menu/healthysalad",healthysalad,name="healthysalad"),
    path("menu/hotdrink",hotdrink,name="hotdrink"),
    path("menu/icetea",icetea,name="icetea"),
    path("menu/mocktail",mocktail,name="mocktail"),
    path("menu/pancakes",pancakes,name="pancakes"),
    path("menu/raita",raita,name="raita"),
    path("menu/shake",shake,name="shake"),
    path("menu/bands",bands,name="bands"),

]
